export const products = [
  {
    id: 1,
    name: "product1",
    price: 14.56,
    imageUrl: "./src/image/product-1.jpg",
  },
  {
    id: 2,
    name: "product2",
    price: 25.96,
    imageUrl: "./src/image/product-2.jpg",
  },
  {
    id: 3,
    name: "product3",
    price: 40,
    imageUrl: "./src/image/product-3.jpg",
  },
  {
    id: 4,
    name: "product4",
    price: 60.2,
    imageUrl: "./src/image/product-4.jpg",
  },
  {
    id: 5,
    name: "product5",
    price: 32.5,
    imageUrl: "./src/image/product-5.jpg",
  },
  {
    id: 6,
    name: "product6",
    price: 75.5,
    imageUrl: "./src/image/product-6.jpg",
  },
  {
    id: 8,
    name: "product8",
    price: 45.5,
    imageUrl: "./src/image/product-8.jpg",
  },
  {
    id: 9,
    name: "product9",
    price: 193.8,
    imageUrl: "./src/image/product-9.jpg",
  },
  {
    id: 10,
    name: "product10",
    price: 193.8,
    imageUrl: "./src/image/product-10.jpg",
  },
  {
    id: 11,
    name: "product11",
    price: 20,
    imageUrl: "./src/image/product-11.jpg",
  },
  {
    id: 12,
    name: "product12",
    price: 546.5,
    imageUrl: "./src/image/product-12.jpg",
  },
  {
    id: 13,
    name: "product13",
    price: 546.9,
    imageUrl: "./src/image/product-13.jpg",
  },
  {
    id: 14,
    name: "product14",
    price: 16.5,
    imageUrl: "./src/image/product-14.jpg",
  },
  {
    id: 15,
    name: "product15",
    price: 20.2,
    imageUrl: "./src/image/product-15.jpg",
  },
  {
    id: 16,
    name: "product16",
    price: 20.9,
    imageUrl: "./src/image/product-16.jpg",
  },
  {
    id: 17,
    name: "product17",
    price: 30.9,
    imageUrl: "./src/image/product-17.jpg",
  },
  {
    id: 18,
    name: "product18",
    price: 38.19,
    imageUrl: "./src/image/product-18.jpg",
  },
  {
    id: 19,
    name: "product19",
    price: 66.5,
    imageUrl: "./src/image/product-19.jpg",
  },
  {
    id: 20,
    name: "product20",
    price: 18.2,
    imageUrl: "./src/image/product-20.jpg",
  },
  {
    id: 21,
    name: "product21",
    price: 65.5,
    imageUrl: "./src/image/product-21.jpg",
  },
  {
    id: 22,
    name: "product22",
    price: 75.5,
    imageUrl: "./src/image/product-22.jpg",
  },
  {
    id: 23,
    name: "product23",
    price: 75.9,
    imageUrl: "./src/image/product-23.jpg",
  },
  {
    id: 24,
    name: "product24",
    price: 10.3,
    imageUrl: "./src/image/product-24.jpg",
  },
  {
    id: 25,
    name: "product25",
    price: 10.4,
    imageUrl: "./src/image/product-25.jpg",
  },
  {
    id: 26,
    name: "product26",
    price: 46.2,
    imageUrl: "./src/image/product-26.jpg",
  },
  {
    id: 27,
    name: "product27",
    price: 49.2,
    imageUrl: "./src/image/product-27.jpg",
  },
  {
    id: 28,
    name: "product28",
    price: 456.9,
    imageUrl: "./src/image/product-28.jpg",
  },
  {
    id: 29,
    name: "product29",
    price: 2.3,
    imageUrl: "./src/image/product-29.jpg",
  },
  {
    id: 30,
    name: "product30",
    price: 99.9,
    imageUrl: "./src/image/product-30.jpg",
  },
  {
    id: 31,
    name: "product31",
    price: 85.5,
    imageUrl: "./src/image/product-31.jpg",
  },
  {
    id: 32,
    name: "product32",
    price: 85.9,
    imageUrl: "./src/image/product-32.jpg",
  },
  {
    id: 33,
    name: "product33",
    price: 25.6,
    imageUrl: "./src/image/product-33.jpg",
  },
  {
    id: 34,
    name: "product34",
    price: 27.4,
    imageUrl: "./src/image/product-34.jpg",
  },
  {
    id: 35,
    name: "product35",
    price: 11.2,
    imageUrl: "./src/image/product-35.jpg",
  },
  {
    id: 36,
    name: "product36",
    price: 11.2,
    imageUrl: "./src/image/product-36.jpg",
  },
];
